stages:
  - build
  - test
  - analysis

build-debian:
  image: debian:stable
  script:
    - apt-get update -qq && apt-get install -y -qq coreutils make autoconf automake gcc pkg-config libseccomp-dev libssh-dev valgrind
    - ./autogen.sh
    - ./configure
    - make V=s
    - valgrind --error-exitcode=1 ./src/potd --test --redirect 127.0.0.1:2222:127.0.0.1:22222 --protocol 127.0.0.1:22222:127.0.0.1:33333 --jail 127.0.0.1:33333
    - CFLAGS="-static $CFLAGS" LDFLAGS="-static $LDFLAGS" ./configure
    - make V=s
    - valgrind --error-exitcode=1 ./src/potd --test --redirect 127.0.0.1:2222:127.0.0.1:22222 --protocol 127.0.0.1:22222:127.0.0.1:33333 --jail 127.0.0.1:33333
  stage: build
  artifacts:
    paths:
      - ./src/potd
      - ./config.log

build-arch:
  image: base/archlinux
  script:
    - pacman -Syu --noconfirm coreutils make autoconf automake gcc pkg-config libseccomp libssh valgrind
    - ./autogen.sh
    - ./configure
    - make V=s
    - valgrind --error-exitcode=1 ./src/potd --test --redirect 127.0.0.1:2222:127.0.0.1:22222 --protocol 127.0.0.1:22222:127.0.0.1:33333 --jail 127.0.0.1:33333
    - CFLAGS="-static $CFLAGS" LDFLAGS="-static $LDFLAGS" ./configure
    - make V=s
    - valgrind --error-exitcode=1 ./src/potd --test --redirect 127.0.0.1:2222:127.0.0.1:22222 --protocol 127.0.0.1:22222:127.0.0.1:33333 --jail 127.0.0.1:33333
  stage: test
  artifacts:
    paths:
      - ./src/potd
      - ./config.log

flawfinder:
  image: base/archlinux
  stage: analysis
  script:
    - pacman -Syu --noconfirm flawfinder
    - flawfinder --minlevel=3 -QD .
    - flawfinder --inputs --minlevel=3 -QD .
    - flawfinder --html --minlevel=3 . >./flawfinder.html
    - flawfinder --html --inputs --minlevel=3 . >./flawfinder_inputs.html
  artifacts:
    paths:
      - ./flawfinder.html
      - ./flawfinder_inputs.html

cppcheck:
  image: base/archlinux
  stage: analysis
  script:
    - pacman -Syu --noconfirm cppcheck
    - cppcheck --enable=all --inconclusive --std=posix .
