language: c
sudo: required

os:
  - linux

compiler:
  - gcc

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y -qq coreutils make autoconf automake gcc pkg-config valgrind wget libssl-dev
    - wget 'https://www.libssh.org/files/0.7/libssh-0.7.5.tar.xz' -O ./libssh-0.7.5.tar.xz
    - tar -xvf ./libssh-0.7.5.tar.xz
    - cd ./libssh-0.7.5 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make && sudo make install && cd ../..

after_failure:
    - cat config.log

script:
    - ./autogen.sh
    - CFLAGS="-DCAP_AUDIT_READ=0 -DCAP_AUDIT_WRITE=0" ./configure
    - make V=s
    - TERM=linux valgrind --error-exitcode=1 ./src/potd --test --redirect 127.0.0.1:2222:127.0.0.1:22222 --protocol 127.0.0.1:22222:127.0.0.1:33333 --jail 127.0.0.1:33333
